### ISSUE TITLE
Crash on world start up

### ISSUE THREAD

**Issue by mjra007** [Um-Mitternacht/Bewitchment#129]
I took a look at the log and it seems to occur when trying to spawn an entity.
### Expected Behavior
Entering a world shouldn't crash you.

### Actual Behavior
Entering any world crashes me

### Steps to Reproduce
Create a world.
Launch world.

### Version of Minecraft, Bewitchment, Forge, and Baubles
1.12.2, 1.12.2-0.0.16, 14.23.5.2796, 1.12.1.5.2

### Logs, in the event of a crash
Log
https://pastebin.com/jxF2QBqD
Crash
<details>
  <summary>Click to expand</summary>
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 12/10/18 8:02 PM
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at net.minecraft.world.WorldEntitySpawner.func_77191_a(WorldEntitySpawner.java:297)
	at net.minecraft.world.gen.ChunkGeneratorOverworld.func_185931_b(ChunkGeneratorOverworld.java:466)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1019)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:999)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157)
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:344)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:142)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:156)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 669866512 bytes (638 MB) / 1431306240 bytes (1365 MB) up to 5726797824 bytes (5461 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6144m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.5.2796 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID          | Version      | Source                        | Signature                                |
	|:------ |:----------- |:------------ |:----------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft   | 1.12.2       | minecraft.jar                 | None                                     |
	| LCHIJA | mcp         | 9.42         | minecraft.jar                 | None                                     |
	| LCHIJA | FML         | 8.0.99.99    | forge-1.12.2-14.23.5.2796.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge       | 14.23.5.2796 | forge-1.12.2-14.23.5.2796.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | baubles     | 1.5.2        | Baubles-1.12-1.5.2.jar        | None                                     |
	| LCHIJA | patchouli   | 1.0-12       | Patchouli-1.0-12.jar          | None                                     |
	| LCHIJA | bewitchment | 0.0.16       | Bewitchment-1.12.2-0.0.16.jar | None                                     |

	Loaded coremods (and transformers): 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
</details>

**Comment by weedgoku** [comment]
I have a similar crash. I suspect it's caused by the same thing (something about rendering blindworms?), so I'm commenting here.

Console log of crash: https://pastebin.com/PcZpj60Y

crash-2018-12-11_07.11.10-server.txt: https://pastebin.com/jYU5mSPu

**Comment by mjra007** [comment]
I can confirm this is still happening on 0.0.16.2
