### ISSUE TITLE
my minecraft does not open and I already tested it with just the mods it needs to work and minecraft does not crash before opening

### ISSUE THREAD

**Issue by genilgames** [Um-Mitternacht/Bewitchment#250]

**Comment by genilgames** [comment]
my minecraft does not open and I already tested it with just the mods it needs to work and minecraft does not crash before opening

**Comment by Sunconure11** [comment]
I'm going to need more info than this if I am to help you.

**Comment by genilgames** [comment]
Already decided I had a very old forge and then the version
 0.19.20 still giving the error more error inves to be in the 2/7 of the bar is in the 6/7 of the loading bar hence I tested with the version 0.19.19 and it worked

**Comment by genilgames** [comment]
but here's the crash report Minecraft Crash Report

---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (LLibrary-1.12.2.jar)
Contact their authors BEFORE contacting forge

// Oh - I know what I did wrong!

Time: 2/24/19 3:10 PM
Description: Initializing game

java.lang.RuntimeException: One of more entry values did not copy to the correct id. Check log for details!
	at net.minecraftforge.registries.ForgeRegistry.sync(ForgeRegistry.java:549)
	at net.minecraftforge.registries.GameData.loadRegistry(GameData.java:556)
	at net.minecraftforge.registries.GameData.freezeData(GameData.java:235)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:753)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraftforge.registries.ForgeRegistry.sync(ForgeRegistry.java:549)
	at net.minecraftforge.registries.GameData.loadRegistry(GameData.java:556)
	at net.minecraftforge.registries.GameData.freezeData(GameData.java:235)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:753)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_181, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 136387504 bytes (130 MB) / 455995392 bytes (434 MB) up to 5814616064 bytes (5545 MB)
	JVM Flags: 3 total; -Xmn128M -Xmx5557M -XX:+UseConcMarkSweepGC
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2815 8 mods loaded, 8 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID          | Version      | Source                                     | Signature                                |
	|:------ |:----------- |:------------ |:------------------------------------------ |:---------------------------------------- |
	| LCHIJA | minecraft   | 1.12.2       | minecraft.jar                              | None                                     |
	| LCHIJA | mcp         | 9.42         | minecraft.jar                              | None                                     |
	| LCHIJA | FML         | 8.0.99.99    | forge-1.12.2-14.23.5.2815.jar              | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge       | 14.23.5.2815 | forge-1.12.2-14.23.5.2815.jar              | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | baubles     | 1.5.2        | Baubles-1.12-1.5.2.jar                     | None                                     |
	| LCHIJA | llibrary    | 1.7.7        | LLibrary-1.12.2.jar                        | None                                     |
	| LCHIJA | patchouli   | 1.0-17       | Patchouli-1.0-17.jar                       | None                                     |
	| LCHIJA | bewitchment | @VERSION@    | Bewitchment-1.12.2-0.0.19.20-indev (1).jar | None                                     |

	Loaded coremods (and transformers): 
llibrary (LLibrary-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 398.82' Renderer: 'GeForce GT 1030/PCIe/SSE2'
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2815
	LWJGL: 2.9.4
	OpenGL: GeForce GT 1030/PCIe/SSE2 GL version 4.6.0 NVIDIA 398.82, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: Português (Brasil)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-4430 CPU @ 3.00GHz

**Comment by genilgames** [comment]
Sorry for the english to use google translate

**Comment by TechnoMysterio** [comment]
This is likely the same as #247, the crash logs look basically identical at least.

**Comment by genilgames** [comment]
but this only happens when I use the latest version of the mod to version 0.19.20 and have to use forge 1.12.2 14.23.5.2815
in case I use the mod version 0.19.19 with the same forge of the certain case be the error forge 1.12.2 14.23.5.2784 in the 3/7 of the bar

**Comment by TechnoMysterio** [comment]
Try installing Rustic into your pack as well, that should allow the game to load up correctly with Bewitchment 0.0.19.20.

**Comment by genilgames** [comment]
thank you  it worked out
