### ISSUE TITLE
Bewitchment is using deprecated IMC variation:add

### ISSUE THREAD

**Issue by ghost** [Um-Mitternacht/Bewitchment#346]
### Basic Information:

- Minecraft Version: 1.12.2
- Minecraft Forge Version: 1.12.2-14.23.5.2838
- SpongeForge Version: 1.12.2-2825-7.1.6-RC3716
- Java Version: 1.8.0

### Crash Log:

```
[19:33:57] [Server thread/WARN] [Chisel]: Mod bewitchment is using deprecated IMC variation:add! This IMC type may be removed soon, please notify the author of this mod.
[19:33:57] [Server thread/ERROR] [Chisel]: Could not handle data nethersteel|bewitchment:nethersteel_chisel|11 for IMC type ADD_VARIATION. This was sent from mod bewitchment.
!! This is a bug in that mod !!
Swallowing error and continuing...
[19:33:57] [Server thread/INFO] [STDERR]: [team.chisel.common.integration.imc.IMCHandler:handle:148]: java.lang.ArrayIndexOutOfBoundsException: 11
[19:33:57] [Server thread/INFO] [STDERR]: [team.chisel.common.integration.imc.IMCHandler:handle:148]: 	at com.bewitchment.common.integration.chisel.BlockNetherSteelChiseled.func_176203_a(BlockNetherSteelChiseled.java:32)
[19:33:57] [Server thread/INFO] [STDERR]: [team.chisel.common.integration.imc.IMCHandler:handle:148]: 	at team.chisel.common.integration.imc.IMCHandler.handle(IMCHandler.java:91)
[19:33:57] [Server thread/INFO] [STDERR]: [team.chisel.common.integration.imc.IMCHandler:handle:148]: 	at team.chisel.common.integration.imc.IMCHandler.handleMessage(IMCHandler.java:42)
[19:33:57] [Server thread/INFO] [STDERR]: [team.chisel.common.integration.imc.IMCHandler:handle:148]: 	at team.chisel.Chisel.onIMC(Chisel.java:217)
[19:33:57] [Server thread/INFO] [STDERR]: [team.chisel.common.integration.imc.IMCHandler:handle:148]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:33:57] [Server thread/INFO] [STDERR]: [team.chisel.common.integration.imc.IMCHandler:handle:148]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[19:33:57] [Server thread/INFO] [STDERR]: [team.chisel.common.integration.imc.IMCHandler:handle:148]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[19:33:57] [Server thread/INFO] [STDERR]: [team.chisel.common.integration.imc.IMCHandler:handle:148]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[19:33:57] [Server thread/INFO] [STDERR]: [team.chisel.common.integration.imc.IMCHandler:handle:148]: 	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
[19:33:57] [Server thread/INFO] [STDERR]: [team.chisel.common.integration.imc.IMCHandler:handle:148]: 	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
[19:33:57] [Server thread/INFO] [STDERR]: [team.chisel.common.integration.imc.IMCHandler:handle:148]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[19:33:57] [Server thread/INFO] [STDERR]: [team.chisel.common.integration.imc.IMCHandler:handle:148]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[19:33:57] [Server thread/INFO] [STDERR]: [team.chisel.common.integration.imc.IMCHandler:handle:148]: 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
[19:33:57] [Server thread/INFO] [STDERR]: [team.chisel.common.integration.imc.IMCHandler:handle:148]: 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
[19:33:57] [Server thread/INFO] [STDERR]: [team.chisel.common.integration.imc.IMCHandler:handle:148]: 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
[19:33:57] [Server thread/INFO] [STDERR]: [team.chisel.common.integration.imc.IMCHandler:handle:148]: 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
[19:33:57] [Server thread/INFO] [STDERR]: [team.chisel.common.integration.imc.IMCHandler:handle:148]: 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
[19:33:57] [Server thread/INFO] [STDERR]: [team.chisel.common.integration.imc.IMCHandler:handle:148]: 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
[19:33:57] [Server thread/INFO] [STDERR]: [team.chisel.common.integration.imc.IMCHandler:handle:148]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
[19:33:57] [Server thread/INFO] [STDERR]: [team.chisel.common.integration.imc.IMCHandler:handle:148]: 	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
[19:33:57] [Server thread/INFO] [STDERR]: [team.chisel.common.integration.imc.IMCHandler:handle:148]: 	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
[19:33:57] [Server thread/INFO] [STDERR]: [team.chisel.common.integration.imc.IMCHandler:handle:148]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:33:57] [Server thread/INFO] [STDERR]: [team.chisel.common.integration.imc.IMCHandler:handle:148]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[19:33:57] [Server thread/INFO] [STDERR]: [team.chisel.common.integration.imc.IMCHandler:handle:148]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[19:33:57] [Server thread/INFO] [STDERR]: [team.chisel.common.integration.imc.IMCHandler:handle:148]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[19:33:57] [Server thread/INFO] [STDERR]: [team.chisel.common.integration.imc.IMCHandler:handle:148]: 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
[19:33:57] [Server thread/INFO] [STDERR]: [team.chisel.common.integration.imc.IMCHandler:handle:148]: 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
[19:33:57] [Server thread/INFO] [STDERR]: [team.chisel.common.integration.imc.IMCHandler:handle:148]: 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
[19:33:57] [Server thread/INFO] [STDERR]: [team.chisel.common.integration.imc.IMCHandler:handle:148]: 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
[19:33:57] [Server thread/INFO] [STDERR]: [team.chisel.common.integration.imc.IMCHandler:handle:148]: 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
[19:33:57] [Server thread/INFO] [STDERR]: [team.chisel.common.integration.imc.IMCHandler:handle:148]: 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
[19:33:57] [Server thread/INFO] [STDERR]: [team.chisel.common.integration.imc.IMCHandler:handle:148]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
[19:33:57] [Server thread/INFO] [STDERR]: [team.chisel.common.integration.imc.IMCHandler:handle:148]: 	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:320)
[19:33:57] [Server thread/INFO] [STDERR]: [team.chisel.common.integration.imc.IMCHandler:handle:148]: 	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:747)
[19:33:57] [Server thread/INFO] [STDERR]: [team.chisel.common.integration.imc.IMCHandler:handle:148]: 	at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:108)
[19:33:57] [Server thread/INFO] [STDERR]: [team.chisel.common.integration.imc.IMCHandler:handle:148]: 	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:338)
[19:33:57] [Server thread/INFO] [STDERR]: [team.chisel.common.integration.imc.IMCHandler:handle:148]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:219)
[19:33:57] [Server thread/INFO] [STDERR]: [team.chisel.common.integration.imc.IMCHandler:handle:148]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
[19:33:57] [Server thread/INFO] [STDERR]: [team.chisel.common.integration.imc.IMCHandler:handle:148]: 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by Sunconure11** [comment]
We're aware of this, and it has been resolved in the rewrite.

**Comment by ghost** [comment]
Thank you for the swift response!
