### ISSUE TITLE
Parsing error loading built-in advancement

### ISSUE THREAD

**Issue by ghost** [Um-Mitternacht/Bewitchment#347]
### First of all; some basic information.

- Minecraft Version: 1.12.2
- Minecraft Forge Version: 1.12.2-14.23.5.2838
- SpongeForge Version: 1.12.2-2825-7.1.6-RC3716
- Java Version: 1.8.0

### Parsing Error regarding the advancement through Unknown Recipe:
`[19:34:05] [Server thread/WARN] [net.minecraft.world.storage.loot.LootTableManager]: Couldn't find resource table scollectibles:loot_tables
[19:34:06] [Server thread/ERROR] [FML]: Parsing error loading built-in advancement bewitchment:recipes/ritual_chalk
com.google.gson.JsonSyntaxException: Unknown recipe 'bewitchment:ritual_chalk'
	at net.minecraft.advancements.AdvancementRewards$Deserializer.deserialize(AdvancementRewards.java:171) ~[l$a.class:?]
	at net.minecraft.advancements.AdvancementRewards$Deserializer.deserialize(AdvancementRewards.java:147) ~[l$a.class:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[TreeTypeAdapter.class:?]
	at com.google.gson.Gson.fromJson(Gson.java:887) ~[Gson.class:?]
	at com.google.gson.Gson.fromJson(Gson.java:952) ~[Gson.class:?]
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[TreeTypeAdapter$GsonContextImpl.class:?]
	at net.minecraft.util.JsonUtils.deserializeClass(SourceFile:439) ~[rc.class:?]
	at net.minecraft.util.JsonUtils.deserializeClass(SourceFile:455) ~[rc.class:?]
	at net.minecraft.advancements.Advancement$Builder.deserialize(SourceFile:203) ~[i$a.class:?]
	at net.minecraft.advancements.AdvancementManager$1.deserialize(AdvancementManager.java:50) ~[ns$1.class:?]
	at net.minecraft.advancements.AdvancementManager$1.deserialize(AdvancementManager.java:46) ~[ns$1.class:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[TreeTypeAdapter.class:?]
	at net.minecraft.util.JsonUtils.gsonDeserialize(SourceFile:492) ~[rc.class:?]
	at net.minecraft.util.JsonUtils.fromJson(SourceFile:532) ~[rc.class:?]
	at net.minecraftforge.common.ForgeHooks.lambda$loadAdvancements$0(ForgeHooks.java:1369) ~[ForgeHooks.class:?]
	at net.minecraftforge.common.crafting.CraftingHelper.findFiles(CraftingHelper.java:821) [CraftingHelper.class:?]
	at net.minecraftforge.common.ForgeHooks.loadAdvancements(ForgeHooks.java:1351) [ForgeHooks.class:?]
	at net.minecraftforge.common.ForgeHooks.loadAdvancements(ForgeHooks.java:1325) [ForgeHooks.class:?]
	at net.minecraft.advancements.AdvancementManager.reload(AdvancementManager.java:69) [ns.class:?]
	at net.minecraft.advancements.AdvancementManager.<init>(AdvancementManager.java:60) [ns.class:?]
	at net.minecraft.world.WorldServer.init(WorldServer.java:156) [oo.class:?]
	at org.spongepowered.common.world.WorldManager.createWorldFromProperties(WorldManager.java:816) [WorldManager.class:1.12.2-2825-7.1.6-RC3716]
	at org.spongepowered.common.world.WorldManager.loadAllWorlds(WorldManager.java:784) [WorldManager.class:1.12.2-2825-7.1.6-RC3716]
	at net.minecraft.server.MinecraftServer.loadAllWorlds(MinecraftServer.java:3549) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:270) [nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]`

### Unknown Recipe:
`[19:34:08] [Server thread/WARN] [net.minecraft.world.storage.loot.LootTableManager]: Couldn't find resource table scollectibles:loot_tables
[19:34:08] [Server thread/ERROR] [FML]: Parsing error loading built-in advancement bewitchment:recipes/ritual_chalk
com.google.gson.JsonSyntaxException: Unknown recipe 'bewitchment:ritual_chalk'
	at net.minecraft.advancements.AdvancementRewards$Deserializer.deserialize(AdvancementRewards.java:171) ~[l$a.class:?]
	at net.minecraft.advancements.AdvancementRewards$Deserializer.deserialize(AdvancementRewards.java:147) ~[l$a.class:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[TreeTypeAdapter.class:?]
	at com.google.gson.Gson.fromJson(Gson.java:887) ~[Gson.class:?]
	at com.google.gson.Gson.fromJson(Gson.java:952) ~[Gson.class:?]
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[TreeTypeAdapter$GsonContextImpl.class:?]
	at net.minecraft.util.JsonUtils.deserializeClass(SourceFile:439) ~[rc.class:?]
	at net.minecraft.util.JsonUtils.deserializeClass(SourceFile:455) ~[rc.class:?]
	at net.minecraft.advancements.Advancement$Builder.deserialize(SourceFile:203) ~[i$a.class:?]
	at net.minecraft.advancements.AdvancementManager$1.deserialize(AdvancementManager.java:50) ~[ns$1.class:?]
	at net.minecraft.advancements.AdvancementManager$1.deserialize(AdvancementManager.java:46) ~[ns$1.class:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[TreeTypeAdapter.class:?]
	at net.minecraft.util.JsonUtils.gsonDeserialize(SourceFile:492) ~[rc.class:?]
	at net.minecraft.util.JsonUtils.fromJson(SourceFile:532) ~[rc.class:?]
	at net.minecraftforge.common.ForgeHooks.lambda$loadAdvancements$0(ForgeHooks.java:1369) ~[ForgeHooks.class:?]
	at net.minecraftforge.common.crafting.CraftingHelper.findFiles(CraftingHelper.java:821) [CraftingHelper.class:?]
	at net.minecraftforge.common.ForgeHooks.loadAdvancements(ForgeHooks.java:1351) [ForgeHooks.class:?]
	at net.minecraftforge.common.ForgeHooks.loadAdvancements(ForgeHooks.java:1325) [ForgeHooks.class:?]
	at net.minecraft.advancements.AdvancementManager.reload(AdvancementManager.java:69) [ns.class:?]
	at net.minecraft.advancements.AdvancementManager.<init>(AdvancementManager.java:60) [ns.class:?]
	at net.minecraft.world.WorldServer.init(WorldServer.java:156) [oo.class:?]
	at org.spongepowered.common.world.WorldManager.createWorldFromProperties(WorldManager.java:816) [WorldManager.class:1.12.2-2825-7.1.6-RC3716]
	at org.spongepowered.common.world.WorldManager.loadAllWorlds(WorldManager.java:784) [WorldManager.class:1.12.2-2825-7.1.6-RC3716]
	at net.minecraft.server.MinecraftServer.loadAllWorlds(MinecraftServer.java:3549) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:270) [nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]`

**Comment by Sunconure11** [comment]
It's the result of an unused advancement. This will not be a problem in the rewrite.
