### ISSUE TITLE
Crash during startup.

### ISSUE THREAD

**Issue by Carvercarver1** [Um-Mitternacht/Bewitchment#350]
Got a weird crash. My theory: forge version or a real bug.  Or something else, because it would've told me about forge version.
Which version of forge does it (mod) require? Did this run on 2772 version. There's no strict description on the version. 
_______________________________________________________________________________________
Description: Initializing game

java.lang.NoClassDefFoundError: net/minecraftforge/event/entity/living/PotionEvent$PotionApplicableEvent
    at java.lang.Class.getDeclaredConstructors0(Native Method)
    at java.lang.Class.privateGetDeclaredConstructors(Class.java:2663)
    at java.lang.Class.getConstructor0(Class.java:3067)
    at java.lang.Class.getDeclaredConstructor(Class.java:2170)
    at net.minecraftforge.fml.relauncher.ReflectionHelper.findConstructor(ReflectionHelper.java:255)
    at net.minecraftforge.fml.common.registry.EntityEntryBuilder$ConstructorFactory.<init>(EntityEntryBuilder.java:296)
    at net.minecraftforge.fml.common.registry.EntityEntryBuilder$1.<init>(EntityEntryBuilder.java:264)
    at net.minecraftforge.fml.common.registry.EntityEntryBuilder.build(EntityEntryBuilder.java:264)
    at com.bewitchment.common.entity.ModEntities.registerWithEgg(ModEntities.java:85)
    at com.bewitchment.common.entity.ModEntities.<clinit>(ModEntities.java:64)
    at com.bewitchment.common.entity.ModEntities$RegistrationHandler.onEvent(ModEntities.java:123)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_143_RegistrationHandler_onEvent_Register.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:787)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:628)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
    at net.minecraft.client.Minecraft.init(Minecraft.java:466)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3930)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: net.minecraftforge.event.entity.living.PotionEvent$PotionApplicableEvent
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 27 more
Caused by: java.lang.NullPointerException

**Comment by MoriyaShiine** [comment]
Needs a later forge version, but this won't be an issue in the rewrite.

**Comment by Carvercarver1** [comment]
That was surprisingly fast. 

Thanks. I guess I'll wait for the rewrite (altrough, not sure when this will come out).
