### ISSUE TITLE
Fortune's Favor Deletes Certain TileEntities

### ISSUE THREAD

**Issue by FoxMcloud5655** [Um-Mitternacht/Bewitchment#482]
For this report, I'll use the Extra Utilities 2 Generators as an example.

### Expected Behavior

When mined out, the generator drops as normal.

### Actual Behavior

When mined out, the generator drops nothing and causes a crash.

### Steps to Reproduce

Place down an Extra Utilities 2 Generator of any type, equip the Fortune's Favor bauble, and mine the generator with an iron or higher pickaxe.

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used

Minecraft: 1.12.2
Bewitchment: 0.0.21.5
Forge: 14.23.5.2847
Patchouli: 1.0-20
Baubles: 1.5.2

### Logs

```
Time: 2019-12-30 13:18:42 CST
Description: Error executing task

java.util.concurrent.ExecutionException: java.lang.UnsupportedOperationException
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:192)
    at net.minecraft.util.Util.runTask(SourceFile:531)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:723)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:185)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.UnsupportedOperationException
    at com.google.common.collect.ImmutableCollection.clear(ImmutableCollection.java:294)
    at com.bewitchment.common.item.equipment.baubles.ItemFortuneFavor.onBlockDrop(ItemFortuneFavor.java:30)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1699_ItemFortuneFavor_onBlockDrop_HarvestDropsEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.event.ForgeEventFactory.fireBlockHarvesting(ForgeEventFactory.java:344)
    at net.minecraft.block.Block.dropBlockAsItemWithChance(Block.java:572)
    at net.minecraft.block.Block.dropBlockAsItem(Block.java:564)
    at net.minecraft.block.Block.harvestBlock(Block.java:735)
    at com.rwtema.extrautils2.backend.XUBlock.harvestBlock(XUBlock.java:350)
    at net.minecraft.server.management.PlayerInteractionManager.tryHarvestBlock(PlayerInteractionManager.java:327)
    at net.minecraft.server.management.PlayerInteractionManager.blockRemoving(PlayerInteractionManager.java:244)
    at net.minecraft.network.NetHandlerPlayServer.processPlayerDigging(NetHandlerPlayServer.java:704)
    at net.minecraft.network.play.client.CPacketPlayerDigging.processPacket(SourceFile:40)
    at net.minecraft.network.play.client.CPacketPlayerDigging.processPacket(SourceFile:10)
    at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at net.minecraft.util.Util.runTask(SourceFile:529)
    ... 5 more
```

**Comment by anqingchen** [comment]
Should be fixed in 382f4329b948269a671f46df88bc2c8355049a32
