### ISSUE TITLE
crash with just enough ids

### ISSUE THREAD

**Issue by pibblesarethebest** [Um-Mitternacht/Bewitchment#508]
### Expected Behavior
the game loads to the main menu

### Actual Behavior
the game crashes before it can properly load

### Steps to Reproduce
install bewitchment and required dependencies alongside just enough ids

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used
bewitchment: 1.12.2-0.0.21.7
forge: 14.23.5.2847
patchouli: 1.0-20
baubles: 1.12-1.5.2

### Screenshots encouraged
none

### Logs, in the event of a crash
// There are four lights!

Time: 1/31/20 12:33 AM
Description: Initializing game

java.lang.IllegalAccessError: tried to access class org.spongepowered.asm.mixin.transformer.MixinTransformer from class net.minecraftforge.fml.common.Loader
	at net.minecraftforge.fml.common.Loader.handler$zza000$beforeConstructingMods(Loader.java:1132)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:594)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraftforge.fml.common.Loader.handler$zza000$beforeConstructingMods(Loader.java:1132)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:594)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by Sunconure11** [comment]
We're aware of this issue. I'm waiting on @anqingchen to fix the mixins issue before I can push out a hotfix. Downgrade for now, as that build is broken.

**Comment by MagicMaxcer** [comment]
I have the same crash report

**Comment by pibblesarethebest** [comment]
downgrade to what build?

**Comment by Sunconure11** [comment]
Crash is related to one of the devs updating mixin to a version incompatible with 1.12.2
