### ISSUE TITLE
opening 

### ISSUE THREAD

**Issue by RuneKeeper666** [Um-Mitternacht/Bewitchment#514]
### Expected Behavior
Minecraft start up

### Actual Behavior

Game crash
### Steps to Reproduce

open launcher with these mods
### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used
1.12.2, 1.12.2-0.0.21.10.jar, 1.12.2-14.23.5.2775, Patchouli-1.0-20, 1.12-1.5.2

### Logs, in the event of a crash

---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  AstralCore (astralsorcery-1.12.2-1.10.3.jar)
  BewitchmentFMLLoadingPlugin (bewitchment-1.12.2-0.0.21.10.jar)
Contact their authors BEFORE contacting forge

// I just don't know what went wrong :(

Time: 2/10/20 5:36 PM
Description: Initializing game

java.lang.NoSuchMethodError: net.minecraftforge.fml.relauncher.ReflectionHelper.findField(Ljava/lang/Class;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/reflect/Field;
	at com.bewitchment.common.potion.PotionRubedo.<clinit>(PotionRubedo.java:28)
	at com.bewitchment.registry.ModPotions.<clinit>(ModPotions.java:16)
	at com.bewitchment.registry.ModRegistries.registerBrews(ModRegistries.java:245)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_19_ModRegistries_registerBrews_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:787)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:628)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.bewitchment.common.potion.PotionRubedo.<clinit>(PotionRubedo.java:28)
	at com.bewitchment.registry.ModPotions.<clinit>(ModPotions.java:16)
	at com.bewitchment.registry.ModRegistries.registerBrews(ModRegistries.java:245)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_19_ModRegistries_registerBrews_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:787)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:628)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Mac OS X (x86_64) version 10.13.6
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 268375656 bytes (255 MB) / 872415232 bytes (832 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 7 total; -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2775 Optifine OptiFine_1.12.2_HD_U_F5 15 mods loaded, 15 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID              | Version      | Source                            | Signature                                |
	|:----- |:--------------- |:------------ |:--------------------------------- |:---------------------------------------- |
	| UCH   | minecraft       | 1.12.2       | minecraft.jar                     | None                                     |
	| UCH   | mcp             | 9.42         | minecraft.jar                     | None                                     |
	| UCH   | FML             | 8.0.99.99    | forge-1.12.2-14.23.5.2775.jar     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge           | 14.23.5.2775 | forge-1.12.2-14.23.5.2775.jar     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | organiccreepers | 1.12.2       | [1.12.2]OrganicCreepers-1.2.5.jar | None                                     |
	| UCH   | baubles         | 1.5.2        | Baubles-1.12-1.5.2.jar            | None                                     |
	| UCH   | astralsorcery   | 1.10.3       | astralsorcery-1.12.2-1.10.3.jar   | a0f0b759d895c15ceb3e3bcb5f3c2db7c582edf0 |
	| UCH   | patchouli       | 1.0-20       | Patchouli-1.0-20.jar              | None                                     |
	| UCH   | bewitchment     | 0.21.10      | bewitchment-1.12.2-0.0.21.10.jar  | None                                     |
	| UCH   | chiselsandbits  | 14.33        | chiselsandbits-14.33.jar          | None                                     |
	| UCH   | cfm             | 6.3.1        | furniture-6.3.1-1.12.2.jar        | None                                     |
	| UCH   | jei             | 4.15.0.275   | jei_1.12.2-4.15.0.275.jar         | None                                     |
	| UCH   | treechoppin     | 1.0.0        | TreeChoppin-1.12.2-1.0.0.jar      | None                                     |
	| UCH   | llibrary        | 1.7.19       | llibrary-1.7.19-1.12.2.jar        | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| UCH   | jurassicraft    | 2.1.23       | JurassiCraft-1.12.2-2.1.23.jar    | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
AstralCore (astralsorcery-1.12.2-1.10.3.jar)
  
BewitchmentFMLLoadingPlugin (bewitchment-1.12.2-0.0.21.10.jar)
  
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '2.1 ATI-1.68.24' Renderer: 'AMD Radeon HD 6770M OpenGL Engine'
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2775
	LWJGL: 2.9.2
	OpenGL: AMD Radeon HD 6770M OpenGL Engine GL version 2.1 ATI-1.68.24, ATI Technologies Inc.
	GL Caps: VboRegions not supported, missing: OpenGL 1.3, ARB_copy_buffer
Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: vanilla, file/Dragon+Dance+1.14.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-2500S CPU @ 2.70GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_F5
	OptiFine Build: 20191204-141934
	Render Distance Chunks: 20
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 2.1 ATI-1.68.24
	OpenGlRenderer: AMD Radeon HD 6770M OpenGL Engine
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 4

**Comment by Sunconure11** [comment]
Uh dude this report is entirely blank

**Comment by RuneKeeper666** [comment]
sorry fixed it

**Comment by RuneKeeper666** [comment]
fixed it being blank

**Comment by RuneKeeper666** [comment]
> Uh dude this report is entirely blank

Hey just so you know fixed it being blank sorry about that I it was my first time submitting a problem with a mod on git hub

**Comment by Sunconure11** [comment]
Yeah, I saw.

Update Forge to the latest build.
