### ISSUE TITLE
Initializing game crash

### ISSUE THREAD

**Issue by Gjifttann** [Um-Mitternacht/Bewitchment#518]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  BewitchmentFMLLoadingPlugin (bewitchment-1.12.2-0.0.21.8.jar)
Contact their authors BEFORE contacting forge

// You should try our sister game, Minceraft!

Time: 2/16/20 1:26 PM
Description: Initializing game

java.lang.NoSuchMethodError: net.minecraftforge.fml.relauncher.ReflectionHelper.findField(Ljava/lang/Class;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/reflect/Field;
	at com.bewitchment.common.potion.PotionRubedo.<clinit>(PotionRubedo.java:28)
	at com.bewitchment.registry.ModPotions.<clinit>(ModPotions.java:16)
	at com.bewitchment.registry.ModRegistries.registerBrews(ModRegistries.java:247)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_9_ModRegistries_registerBrews_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:787)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:628)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.bewitchment.common.potion.PotionRubedo.<clinit>(PotionRubedo.java:28)
	at com.bewitchment.registry.ModPotions.<clinit>(ModPotions.java:16)
	at com.bewitchment.registry.ModRegistries.registerBrews(ModRegistries.java:247)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_9_ModRegistries_registerBrews_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:787)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:628)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 449851168 bytes (429 MB) / 805306368 bytes (768 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID          | Version      | Source                          | Signature                                |
	|:----- |:----------- |:------------ |:------------------------------- |:---------------------------------------- |
	| UCH   | minecraft   | 1.12.2       | minecraft.jar                   | None                                     |
	| UCH   | mcp         | 9.42         | minecraft.jar                   | None                                     |
	| UCH   | FML         | 8.0.99.99    | forge-1.12.2-14.23.5.2768.jar   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge       | 14.23.5.2768 | forge-1.12.2-14.23.5.2768.jar   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | baubles     | 1.5.2        | Baubles-1.12-1.5.2.jar          | None                                     |
	| UCH   | patchouli   | 1.0-20       | Patchouli-1.0-20.jar            | None                                     |
	| UCH   | bewitchment | 0.21.8       | bewitchment-1.12.2-0.0.21.8.jar | None                                     |

	Loaded coremods (and transformers): 
BewitchmentFMLLoadingPlugin (bewitchment-1.12.2-0.0.21.8.jar)
  
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.6.13559 Compatibility Profile Context 26.20.12028.2' Renderer: 'Radeon RX 570 Series'
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2768
	LWJGL: 2.9.4
	OpenGL: Radeon RX 570 Series GL version 4.6.13559 Compatibility Profile Context 26.20.12028.2, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 6x Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz

**Comment by iceyrazor** [comment]
use the latest version of forge not recommended.

**Comment by ProsperCraft** [comment]
Agreed, use 2847, you can close this issue. Works for me with 2847.
