### ISSUE TITLE
Non fatal, 'fatal' error:  "java.lang.IllegalArgumentException: Invalid UUID string"

### ISSUE THREAD

**Issue by madmax3004** [Um-Mitternacht/Bewitchment#597]
Note: I happened to see this in the server console, but it didn't cause any noticeable issues / crash / bugs.

### Expected Behavior
/

### Actual Behavior
/

### Steps to Reproduce
/

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used
Minecraft: 1.12.2
Bewitchment: 1.12.2-0.0.22.3
Forge: 1.12.2-14.23.5.2854
Patchouli: 1.0-20
Baubles: 1.12-1.5.2

### Screenshots encouraged
/

### Logs, in the event of a crash
`[07:54:25] [Server thread/FATAL] [VanillaFix]: Error executing task
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Invalid UUID string: 
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_252]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_252]
        at net.minecraft.util.Util.runTask(SourceFile:531) [h.class:?]
        at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:723) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
Caused by: java.lang.IllegalArgumentException: Invalid UUID string: 
        at java.util.UUID.fromString(UUID.java:194) ~[?:1.8.0_252]
        at com.bewitchment.api.capability.extendedplayer.ExtendedPlayerHandler.onLivingDeath(ExtendedPlayerHandler.java:135) ~[ExtendedPlayerHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1233_ExtendedPlayerHandler_onLivingDeath_LivingDeathEvent.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?]
        at net.minecraftforge.common.ForgeHooks.onLivingDeath(ForgeHooks.java:615) ~[ForgeHooks.class:14.23.5.2854]
        at net.minecraft.entity.EntityLivingBase.onDeath(EntityLivingBase.java:1168) ~[vp.class:?]
        at net.minecraft.entity.passive.EntityTameable.onDeath(SourceFile:213) ~[wb.class:?]
        at net.minecraft.entity.EntityLivingBase.attackEntityFrom(EntityLivingBase.java:1023) ~[vp.class:?]
        at net.minecraft.entity.passive.EntityAnimal.attackEntityFrom(SourceFile:66) ~[zv.class:?]
        at com.bewitchment.common.entity.util.ModEntityTameable.attackEntityFrom(ModEntityTameable.java:56) ~[ModEntityTameable.class:?]
        at net.minecraft.entity.player.EntityPlayer.attackTargetEntityWithCurrentItem(EntityPlayer.java:1328) ~[aed.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.attackTargetEntityWithCurrentItem(EntityPlayerMP.java:1425) ~[oq.class:?]
        at net.minecraft.network.NetHandlerPlayServer.processUseEntity(NetHandlerPlayServer.java:1092) ~[pa.class:?]
        at net.minecraft.network.play.client.CPacketUseEntity.processPacket(SourceFile:69) ~[li.class:?]
        at net.minecraft.network.play.client.CPacketUseEntity.processPacket(SourceFile:13) ~[li.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_252]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_252]
        at net.minecraft.util.Util.runTask(SourceFile:529) ~[h.class:?]
        ... 5 more`

### If this is a question, developer commentary, or a suggestion, ignore this template
/

**Comment by madmax3004** [comment]
@Sunconure11 Has this been fixed or is it not a Bewitchment bug?

**Comment by Sunconure11** [comment]
Fixed. Curse is apparently being weird with builds though.
