### ISSUE TITLE
Crash with 'Better Portals'

### ISSUE THREAD

**Issue by eikthyrnirmjolk** [Um-Mitternacht/Bewitchment#600]
### Expected Behavior
Game Launches as Normal

### Actual Behavior
Game Crashes as it is launched

### Steps to Reproduce
Installing both 'Better Portals' and 'Bewitchment'. Pressing Start on the laucher.

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used
Minecraft-1.12.2, Bewitchment-0.0.22.3, forge-14.23.5.2854, Patchouli-1.0-20, Baubles-1.5.2

### Logs, in the event of a crash

No Logs Present

**Comment by MoriyaShiine** [comment]
We still can't help you without a crash report.

**Comment by eikthyrnirmjolk** [comment]
Unfortunately that's the issue. There are no crash logs. Could someone possibly try and recreate this, just to see if it is an issue on my end.

This has only started happening with the latest update.

**Comment by Sunconure11** [comment]
Can you at least post any kind of other log? The game should log what's going on.

I have a feeling I know what's going on, though. Update all of your mods. This sometimes happens when two mods are using two different versions of mixins.

**Comment by eikthyrnirmjolk** [comment]
Sorry, but what are mixins? The only loaded mods are bewichtment, it's requirments and better portals. All of which should be up to date.

**Comment by Sunconure11** [comment]
Library used by some mods to do certain tasks that are otherwise impossible. Looking at it, it appears to also be using mixins.

**Comment by eikthyrnirmjolk** [comment]
Ok, will this log do fine?

[15:45:55] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[15:45:55] [main/INFO]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[15:45:55] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[15:45:55] [main/INFO]: Forge Mod Loader version 14.23.5.2854 for Minecraft 1.12.2 loading
[15:45:55] [main/INFO]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_51, running on Windows 10:amd64:10.0, installed at C:\Users\Eikthyrnir\Documents\Curse\Minecraft\Install\runtime\jre-x64
[15:45:55] [main/INFO]: Searching C:\Users\Eikthyrnir\Documents\Curse\Minecraft\Instances\test\mods for mods
[15:45:55] [main/INFO]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from betterportals-0.3.7.7.jar
[15:45:55] [main/INFO]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from bewitchment-1.12.2-0.0.22.4.jar
[15:45:55] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in Forgelin-1.8.4.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[15:45:55] [main/WARN]: The coremod net.shadowfacts.forgelin.preloader.ForgelinPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[15:45:55] [main/WARN]: The coremod ForgelinPlugin (net.shadowfacts.forgelin.preloader.ForgelinPlugin) is not signed!
[15:45:55] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[15:45:55] [main/INFO]: Loading tweak class name org.spongepowered.asm.launch.MixinTweaker
[15:45:55] [main/ERROR]: Catching
org.spongepowered.asm.service.ServiceInitialisationException: ModLauncher is not available
	at org.spongepowered.asm.service.modlauncher.MixinServiceModLauncherBootstrap.bootstrap(MixinServiceModLauncherBootstrap.java:52) ~[bewitchment-1.12.2-0.0.22.4.jar:?]
	at org.spongepowered.asm.service.MixinService.runBootServices(MixinService.java:79) [betterportals-0.3.7.7.jar:?]
	at org.spongepowered.asm.service.MixinService.<init>(MixinService.java:72) [betterportals-0.3.7.7.jar:?]
	at org.spongepowered.asm.service.MixinService.getInstance(MixinService.java:92) [betterportals-0.3.7.7.jar:?]
	at org.spongepowered.asm.service.MixinService.boot(MixinService.java:102) [betterportals-0.3.7.7.jar:?]
	at org.spongepowered.asm.launch.MixinBootstrap.<clinit>(MixinBootstrap.java:76) [betterportals-0.3.7.7.jar:?]
	at org.spongepowered.asm.launch.MixinTweaker.<init>(MixinTweaker.java:44) [betterportals-0.3.7.7.jar:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) [?:1.8.0_51]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [?:1.8.0_51]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) [?:1.8.0_51]
	at java.lang.Class.newInstance(Class.java:442) [?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[15:45:55] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.7.11 Source=file:/C:/Users/Eikthyrnir/Documents/Curse/Minecraft/Instances/test/mods/betterportals-0.3.7.7.jar Service=LaunchWrapper Env=CLIENT
[15:45:55] [main/DEBUG]: Instantiating coremod class BewitchmentFMLLoadingPlugin
[15:45:55] [main/DEBUG]: The coremod com.bewitchment.core.BewitchmentFMLLoadingPlugin requested minecraft version 1.12.2 and minecraft is 1.12.2. It will be loaded.
[15:45:55] [main/WARN]: The coremod BewitchmentFMLLoadingPlugin (com.bewitchment.core.BewitchmentFMLLoadingPlugin) is not signed!
[15:45:55] [main/DEBUG]: Enqueued coremod BewitchmentFMLLoadingPlugin
[15:45:55] [main/WARN]: Tweak class name org.spongepowered.asm.launch.MixinTweaker has already been visited -- skipping
[15:45:55] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[15:45:55] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[15:45:55] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[15:45:55] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[15:45:55] [main/DEBUG]: Injecting coremod FMLCorePlugin \{net.minecraftforge.fml.relauncher.FMLCorePlugin\} class transformers
[15:45:55] [main/TRACE]: Registering transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer
[15:45:56] [main/TRACE]: Registering transformer net.minecraftforge.fml.common.asm.transformers.EventSubscriptionTransformer
[15:45:56] [main/TRACE]: Registering transformer net.minecraftforge.fml.common.asm.transformers.EventSubscriberTransformer
[15:45:56] [main/TRACE]: Registering transformer net.minecraftforge.fml.common.asm.transformers.SoundEngineFixTransformer
[15:45:56] [main/DEBUG]: Injection complete
[15:45:56] [main/DEBUG]: Running coremod plugin for FMLCorePlugin \{net.minecraftforge.fml.relauncher.FMLCorePlugin\}
[15:45:56] [main/DEBUG]: Running coremod plugin FMLCorePlugin
[15:45:57] [main/INFO]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[15:45:57] [main/INFO]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[15:45:57] [main/DEBUG]: Coremod plugin class FMLCorePlugin run successfully
[15:45:57] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[15:45:57] [main/DEBUG]: Injecting coremod FMLForgePlugin \{net.minecraftforge.classloading.FMLForgePlugin\} class transformers
[15:45:57] [main/DEBUG]: Injection complete
[15:45:57] [main/DEBUG]: Running coremod plugin for FMLForgePlugin \{net.minecraftforge.classloading.FMLForgePlugin\}
[15:45:57] [main/DEBUG]: Running coremod plugin FMLForgePlugin
[15:45:57] [main/DEBUG]: Coremod plugin class FMLForgePlugin run successfully
[15:45:57] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[15:45:57] [main/DEBUG]: Injecting coremod ForgelinPlugin \{net.shadowfacts.forgelin.preloader.ForgelinPlugin\} class transformers
[15:45:57] [main/DEBUG]: Injection complete
[15:45:57] [main/DEBUG]: Running coremod plugin for ForgelinPlugin \{net.shadowfacts.forgelin.preloader.ForgelinPlugin\}
[15:45:57] [main/DEBUG]: Running coremod plugin ForgelinPlugin
[15:45:57] [main/DEBUG]: Coremod plugin class ForgelinPlugin run successfully
[15:45:57] [main/INFO]: Calling tweak class org.spongepowered.asm.launch.MixinTweaker
[15:45:57] [main/INFO]: Compatibility level set to JAVA_8
[15:45:57] [main/WARN]: Mixin config mixins.bewitchment.json requires mixin subsystem version 0.8 but 0.7.11 was found. The mixin config will not be applied.
[15:45:57] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: org.spongepowered.asm.launch.MixinInitialisationError: Required mixin config mixins.bewitchment.json requires mixin subsystem version 0.8
[15:45:57] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.mixin.transformer.MixinConfig.checkVersion(MixinConfig.java:417)
[15:45:57] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.mixin.transformer.MixinConfig.onLoad(MixinConfig.java:331)
[15:45:57] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.mixin.transformer.MixinConfig.create(MixinConfig.java:894)
[15:45:57] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:116)
[15:45:57] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.mixin.Mixins.createConfiguration(Mixins.java:91)
[15:45:57] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:78)
[15:45:57] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.platform.MixinPlatformManager.addConfig(MixinPlatformManager.java:282)
[15:45:57] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.platform.MixinPlatformAgentDefault.prepare(MixinPlatformAgentDefault.java:56)
[15:45:57] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.platform.MixinContainer.prepare(MixinContainer.java:103)
[15:45:57] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.platform.MixinPlatformManager.prepare(MixinPlatformManager.java:159)
[15:45:57] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.MixinBootstrap.doInit(MixinBootstrap.java:183)
[15:45:57] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.MixinTweaker.acceptOptions(MixinTweaker.java:53)
[15:45:57] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:114)
[15:45:57] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by Sunconure11** [comment]
Update Better Portals if possible.
