### ISSUE TITLE
Bewitchment Broom "Crash"

### ISSUE THREAD

**Issue by GameDungeon** [Um-Mitternacht/Bewitchment#673]
When I click on any non-chalk block with the broom, vanilla fix detects an error. The game seems to still work fine though.

### Steps to Reproduce
Click on any non-chalk block with a broom, while having vanilla fix installed

### Version of Minecraft
1.12

### Logs, in the event of a crash
Description: Error executing task

java.util.concurrent.ExecutionException: java.lang.NullPointerException
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:192)
    at net.minecraft.util.Util.runTask(SourceFile:531)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:723)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:185)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:819)
Caused by: java.lang.NullPointerException
    at com.bewitchment.api.registry.item.ItemBroom.onItemUse(ItemBroom.java:56)
    at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:889)
    at net.minecraft.item.ItemStack.onItemUse(ItemStack.java:186)
    at net.minecraft.server.management.PlayerInteractionManager.processRightClickBlock(PlayerInteractionManager.java:492)
    at net.minecraft.network.NetHandlerPlayServer.processTryUseItemOnBlock(NetHandlerPlayServer.java:741)
    at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.processPacket(SourceFile:55)
    at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.processPacket(SourceFile:11)
    at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at net.minecraft.util.Util.runTask(SourceFile:529)
    ... 5 more

https://hastebin.com/okolebavoc.txt

**Comment by Sunconure11** [comment]
@unknownbeetle Anything in your broom item changes that could cause this?

**Comment by Sunconure11** [comment]
Try the latest build. See if it still crashes.

**Comment by GameDungeon** [comment]
It seems to be fixed, but I can't 100% confirm
