### ISSUE TITLE
Incompatibility w. BetterPortals

### ISSUE THREAD

**Issue by Shazuli** [Um-Mitternacht/Bewitchment#688]
### Expected Behavior
An incompatibility exists between the mod [BetterPortals](https://www.curseforge.com/minecraft/mc-mods/betterportals) and Bewitchment. A copy of the [log](https://github.com/Um-Mitternacht/Bewitchment/files/5747370/log.txt) and in plain text:
<details>
  <summary>log.txt</summary>
  
  ```
MultiMC version: 0.6.11-1430


Minecraft folder is:
C:/Users/admin/AppData/Roaming/MultiMC/instances/MagicPack2_comp-test/.minecraft


Java path is:
C:/Program Files (x86)/Common Files/Oracle/Java/javapath/javaw.exe


Java is version 1.8.0_221, using 64-bit architecture.


Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  C:/Users/admin/AppData/Roaming/MultiMC/instances/MagicPack2_comp-test/natives

Libraries:
  C:/Users/admin/AppData/Roaming/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  C:/Users/admin/AppData/Roaming/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  C:/Users/admin/AppData/Roaming/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  C:/Users/admin/AppData/Roaming/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  C:/Users/admin/AppData/Roaming/MultiMC/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
  C:/Users/admin/AppData/Roaming/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  C:/Users/admin/AppData/Roaming/MultiMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  C:/Users/admin/AppData/Roaming/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  C:/Users/admin/AppData/Roaming/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  C:/Users/admin/AppData/Roaming/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  C:/Users/admin/AppData/Roaming/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  C:/Users/admin/AppData/Roaming/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  C:/Users/admin/AppData/Roaming/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  C:/Users/admin/AppData/Roaming/MultiMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  C:/Users/admin/AppData/Roaming/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  C:/Users/admin/AppData/Roaming/MultiMC/libraries/io/netty/netty-all/4.1.9.Final/netty-all-4.1.9.Final.jar
  C:/Users/admin/AppData/Roaming/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  C:/Users/admin/AppData/Roaming/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  C:/Users/admin/AppData/Roaming/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  C:/Users/admin/AppData/Roaming/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  C:/Users/admin/AppData/Roaming/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  C:/Users/admin/AppData/Roaming/MultiMC/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
  C:/Users/admin/AppData/Roaming/MultiMC/libraries/com/mojang/realms/1.10.22/realms-1.10.22.jar
  C:/Users/admin/AppData/Roaming/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/admin/AppData/Roaming/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/admin/AppData/Roaming/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/admin/AppData/Roaming/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/admin/AppData/Roaming/MultiMC/libraries/it/unimi/dsi/fastutil/7.1.0/fastutil-7.1.0.jar
  C:/Users/admin/AppData/Roaming/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
  C:/Users/admin/AppData/Roaming/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
  C:/Users/admin/AppData/Roaming/MultiMC/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3.jar
  C:/Users/admin/AppData/Roaming/MultiMC/libraries/net/minecraftforge/forge/1.12.2-14.23.5.2854/forge-1.12.2-14.23.5.2854-universal.jar
  C:/Users/admin/AppData/Roaming/MultiMC/libraries/org/ow2/asm/asm-debug-all/5.2/asm-debug-all-5.2.jar
  C:/Users/admin/AppData/Roaming/MultiMC/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
  C:/Users/admin/AppData/Roaming/MultiMC/libraries/org/jline/jline/3.5.1/jline-3.5.1.jar
  C:/Users/admin/AppData/Roaming/MultiMC/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
  C:/Users/admin/AppData/Roaming/MultiMC/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar
  C:/Users/admin/AppData/Roaming/MultiMC/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
  C:/Users/admin/AppData/Roaming/MultiMC/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
  C:/Users/admin/AppData/Roaming/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2_mc/scala-continuations-library_2.11-1.0.2_mc.jar
  C:/Users/admin/AppData/Roaming/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2_mc/scala-continuations-plugin_2.11.1-1.0.2_mc.jar
  C:/Users/admin/AppData/Roaming/MultiMC/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
  C:/Users/admin/AppData/Roaming/MultiMC/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
  C:/Users/admin/AppData/Roaming/MultiMC/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
  C:/Users/admin/AppData/Roaming/MultiMC/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
  C:/Users/admin/AppData/Roaming/MultiMC/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
  C:/Users/admin/AppData/Roaming/MultiMC/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
  C:/Users/admin/AppData/Roaming/MultiMC/libraries/java3d/vecmath/1.5.2/vecmath-1.5.2.jar
  C:/Users/admin/AppData/Roaming/MultiMC/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  C:/Users/admin/AppData/Roaming/MultiMC/libraries/org/apache/maven/maven-artifact/3.5.3/maven-artifact-3.5.3.jar
  C:/Users/admin/AppData/Roaming/MultiMC/libraries/com/mojang/minecraft/1.12.2/minecraft-1.12.2-client.jar

Native libraries:
  C:/Users/admin/AppData/Roaming/MultiMC/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
  C:/Users/admin/AppData/Roaming/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar
  C:/Users/admin/AppData/Roaming/MultiMC/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3-natives-windows.jar

Mods:
  [✔️] Baubles-1.12-1.5.2
  [✔️] betterportals-0.3.7.7
  [✔️] bewitchment-1.12.2-0.0.22.49
  [✔️] Forgelin-1.8.4
  [✔️] Patchouli-1.0-20

Params:
  --username  --version MultiMC5 --gameDir C:/Users/admin/AppData/Roaming/MultiMC/instances/MagicPack2_comp-test/.minecraft --assetsDir C:/Users/admin/AppData/Roaming/MultiMC/assets --assetIndex 1.12 --uuid  --accessToken  --userType  --versionType release --tweakClass net.minecraftforge.fml.common.launcher.FMLTweaker

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms1024m, -Xmx2048m, -Duser.language=en]


Minecraft process ID: 8472


Using onesix launcher.

[21:07:49] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[21:07:49] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[21:07:49] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[21:07:49] [main/INFO] [FML]: Forge Mod Loader version 14.23.5.2854 for Minecraft 1.12.2 loading
[21:07:49] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_221, running on Windows 10:amd64:10.0, installed at C:\Program Files\Java\jre1.8.0_221
[21:07:49] [main/INFO] [FML]: Searching C:\Users\admin\AppData\Roaming\MultiMC\instances\MagicPack2_comp-test\.minecraft\mods for mods
[21:07:49] [main/INFO] [FML]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from betterportals-0.3.7.7.jar
[21:07:49] [main/INFO] [FML]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from bewitchment-1.12.2-0.0.22.49.jar
[21:07:49] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in Forgelin-1.8.4.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[21:07:49] [main/WARN] [FML]: The coremod net.shadowfacts.forgelin.preloader.ForgelinPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[21:07:49] [main/WARN] [FML]: The coremod ForgelinPlugin (net.shadowfacts.forgelin.preloader.ForgelinPlugin) is not signed!
[21:07:49] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[21:07:49] [main/INFO] [LaunchWrapper]: Loading tweak class name org.spongepowered.asm.launch.MixinTweaker
[21:07:49] [main/ERROR] [mixin]: Catching
org.spongepowered.asm.service.ServiceInitialisationException: ModLauncher is not available
	at org.spongepowered.asm.service.modlauncher.MixinServiceModLauncherBootstrap.bootstrap(MixinServiceModLauncherBootstrap.java:52) ~[bewitchment-1.12.2-0.0.22.49.jar:?]
	at org.spongepowered.asm.service.MixinService.runBootServices(MixinService.java:79) [betterportals-0.3.7.7.jar:?]
	at org.spongepowered.asm.service.MixinService.<init>(MixinService.java:72) [betterportals-0.3.7.7.jar:?]
	at org.spongepowered.asm.service.MixinService.getInstance(MixinService.java:92) [betterportals-0.3.7.7.jar:?]
	at org.spongepowered.asm.service.MixinService.boot(MixinService.java:102) [betterportals-0.3.7.7.jar:?]
	at org.spongepowered.asm.launch.MixinBootstrap.<clinit>(MixinBootstrap.java:76) [betterportals-0.3.7.7.jar:?]
	at org.spongepowered.asm.launch.MixinTweaker.<init>(MixinTweaker.java:44) [betterportals-0.3.7.7.jar:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_221]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) [?:1.8.0_221]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) [?:1.8.0_221]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) [?:1.8.0_221]
	at java.lang.Class.newInstance(Unknown Source) [?:1.8.0_221]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_221]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_221]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_221]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_221]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
[21:07:49] [main/INFO] [mixin]: SpongePowered MIXIN Subsystem Version=0.7.11 Source=file:/C:/Users/admin/AppData/Roaming/MultiMC/instances/MagicPack2_comp-test/.minecraft/mods/betterportals-0.3.7.7.jar Service=LaunchWrapper Env=CLIENT
[21:07:49] [main/WARN] [FML]: The coremod BewitchmentFMLLoadingPlugin (com.bewitchment.core.BewitchmentFMLLoadingPlugin) is not signed!
[21:07:49] [main/WARN] [LaunchWrapper]: Tweak class name org.spongepowered.asm.launch.MixinTweaker has already been visited -- skipping
[21:07:49] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[21:07:49] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[21:07:49] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[21:07:49] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[21:07:51] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[21:07:51] [main/INFO] [FML]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[21:07:51] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[21:07:51] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[21:07:51] [main/INFO] [LaunchWrapper]: Calling tweak class org.spongepowered.asm.launch.MixinTweaker
[21:07:51] [main/INFO] [mixin]: Compatibility level set to JAVA_8
[21:07:51] [main/WARN] [mixin]: Mixin config mixins.bewitchment.json requires mixin subsystem version 0.8 but 0.7.11 was found. The mixin config will not be applied.
[21:07:51] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:199]: Failed to start Minecraft:
[21:07:51] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: java.lang.reflect.InvocationTargetException
[21:07:51] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:07:51] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[21:07:51] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[21:07:51] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[21:07:51] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
[21:07:51] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
[21:07:51] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[21:07:51] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
[21:07:51] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: Caused by: org.spongepowered.asm.launch.MixinInitialisationError: Required mixin config mixins.bewitchment.json requires mixin subsystem version 0.8
[21:07:51] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at org.spongepowered.asm.mixin.transformer.MixinConfig.checkVersion(MixinConfig.java:417)
[21:07:51] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at org.spongepowered.asm.mixin.transformer.MixinConfig.onLoad(MixinConfig.java:331)
[21:07:51] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at org.spongepowered.asm.mixin.transformer.MixinConfig.create(MixinConfig.java:894)
[21:07:51] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:116)
[21:07:51] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at org.spongepowered.asm.mixin.Mixins.createConfiguration(Mixins.java:91)
[21:07:51] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:78)
[21:07:51] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at org.spongepowered.asm.launch.platform.MixinPlatformManager.addConfig(MixinPlatformManager.java:282)
[21:07:51] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at org.spongepowered.asm.launch.platform.MixinPlatformAgentDefault.prepare(MixinPlatformAgentDefault.java:56)
[21:07:51] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at org.spongepowered.asm.launch.platform.MixinContainer.prepare(MixinContainer.java:103)
[21:07:51] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at org.spongepowered.asm.launch.platform.MixinPlatformManager.prepare(MixinPlatformManager.java:159)
[21:07:51] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at org.spongepowered.asm.launch.MixinBootstrap.doInit(MixinBootstrap.java:183)
[21:07:51] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at org.spongepowered.asm.launch.MixinTweaker.acceptOptions(MixinTweaker.java:53)
[21:07:51] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:114)
[21:07:51] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[21:07:51] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	... 8 more
[21:07:51] [main/INFO] [STDOUT]: [org.multimc.EntryPoint:main:37]: Exiting with -1
[21:07:51] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[21:07:51] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[21:07:51] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.SecurityManager.checkExit(Unknown Source)
[21:07:51] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.Runtime.exit(Unknown Source)
[21:07:51] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.System.exit(Unknown Source)
[21:07:51] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at org.multimc.EntryPoint.main(EntryPoint.java:38)
Exception in thread "main" 
Process exited with code 1.
MultiMC: Log upload triggered at: 27 Dec 2020 21:08:28 +0100
```
  
</details>

From what I can extrapolate from the console and answers from the Discord server it appears the issue has to do with Mixins or more rather; conflicting versions. They work fine on their own as well as with the other mods' dependency mods.
### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used
Mod | Version
------ | -------
Minecraft | 1.12.2
Forge | 14.23.5.2854
Bewitchment | 1.12.2-0.0.22.49
Baubles | 1.12-1.5.2
Patchouli | 1.0-20
BetterPortals | 0.3.7.7
Forgelin | 1.8.4

**Comment by Sunconure11** [comment]
Try updating BetterPortals, if possible. This is a mixin issue. See if they have a version using 0.8.

**Comment by Shazuli** [comment]
@Sunconure11 0.3.7.7 is the latest version for BetterPortals for 1.12.2, which was uploaded February. Non-publiced versions for 1.14 exist on their [Github](https://github.com/Johni0702/BetterPortals).

**Comment by Sunconure11** [comment]
They do not appear to have a 1.12.2 build using 0.8 mixin.

**Comment by Shazuli** [comment]
It appears like you can make sure it loads a mod with the required or higher Mixin by renaming it to something that's loaded first. Adding "aa" in the Bewitchment jar apparently solved the issue. Had no idea that's how it works.
