### ISSUE TITLE
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Bewitchment (bewitchment)

### ISSUE THREAD

**Issue by BitterDare** [Um-Mitternacht/Bewitchment#703]
### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used
Minecraft 1.12.2
bewitchment-1.12.2-0.0.22.59
14.23.52854

### Logs, in the event of a crash
---- Minecraft Crash Report ----

WARNING: coremods are present:
  Plugin (NotEnoughIDs-1.5.4.4.jar)
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  BewitchmentFMLLoadingPlugin (bewitchment-1.12.2-0.0.22.59.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.281.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
Contact their authors BEFORE contacting forge

// Ooh. Shiny.

Time: 2/12/21 4:58 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Bewitchment (bewitchment)
Caused by: java.lang.NoClassDefFoundError: com/bewitchment/common/block/BlockCandle
	at com.bewitchment.proxy.ServerProxy.preInit(ServerProxy.java:48)
	at com.bewitchment.proxy.ClientProxy.preInit(ClientProxy.java:103)
	at com.bewitchment.Bewitchment.preInit(Bewitchment.java:95)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: com.bewitchment.common.block.BlockCandle
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 43 more
Caused by: java.lang.NoClassDefFoundError: com/bewitchment/common/block/BlockCandleBase
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 45 more
Caused by: java.lang.ClassNotFoundException: com.bewitchment.common.block.BlockCandleBase
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 49 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 447751872 bytes (427 MB) / 939524096 bytes (896 MB) up to 12884901888 bytes (12288 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx12G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 Optifine OptiFine_1.12.2_HD_U_F5 47 mods loaded, 47 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                   | Version                     | Source                                             | Signature                                |
	|:----- |:-------------------- |:--------------------------- |:-------------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft            | 1.12.2                      | minecraft.jar                                      | None                                     |
	| LCH   | mcp                  | 9.42                        | minecraft.jar                                      | None                                     |
	| LCH   | FML                  | 8.0.99.99                   | forge-1.12.2-14.23.5.2854.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge                | 14.23.5.2854                | forge-1.12.2-14.23.5.2854.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | micdoodlecore        |                             | minecraft.jar                                      | None                                     |
	| LCH   | baubles              | 1.5.2                       | Baubles-1.12-1.5.2.jar                             | None                                     |
	| LCH   | betterplacement      | 1.0.0-1                     | BetterPlacement-1.0.0-1.jar                        | None                                     |
	| LCH   | patchouli            | 1.0-23.6                    | Patchouli-1.0-23.6.jar                             | None                                     |
	| LCH   | thaumcraft           | 6.1.BETA24                  | Thaumcraft-1.12.2-6.1.BETA24.jar                   | None                                     |
	| LCE   | bewitchment          | 0.22.59                     | bewitchment-1.12.2-0.0.22.59.jar                   | None                                     |
	| LC    | bibliocraft          | 2.4.5                       | BiblioCraft[v2.4.5][MC1.12.2].jar                  | None                                     |
	| LC    | chinjufumod          | [1.12.2]5.2.1               | ChinjufuMod[1.12.2]5.2.1.jar                       | None                                     |
	| LC    | ctm                  | MC1.12.2-1.0.2.31           | CTM-MC1.12.2-1.0.2.31.jar                          | None                                     |
	| LC    | chisel               | MC1.12.2-1.0.2.45           | Chisel-MC1.12.2-1.0.2.45.jar                       | None                                     |
	| LC    | chiselsandbits       | 14.33                       | chiselsandbits-14.33.jar                           | None                                     |
	| LC    | codechickenlib       | 3.2.3.358                   | CodeChickenLib-1.12.2-3.2.3.358-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LC    | ebwizardry           | 4.3.4                       | ElectroblobsWizardry-4.3.4-MC1.12.2.jar            | None                                     |
	| LC    | mantle               | 1.12-1.3.3.55               | Mantle-1.12-1.3.3.55.jar                           | None                                     |
	| LC    | twilightforest       | 3.11.1021                   | twilightforest-1.12.2-3.11.1021-universal.jar      | None                                     |
	| LC    | tconstruct           | 1.12.2-2.13.0.183           | TConstruct-1.12.2-2.13.0.183.jar                   | None                                     |
	| LC    | galacticraftcore     | 4.0.2.281                   | GalacticraftCore-1.12.2-4.0.2.281.jar              | None                                     |
	| LC    | galacticraftplanets  | 4.0.2.281                   | Galacticraft-Planets-1.12.2-4.0.2.281.jar          | None                                     |
	| LC    | trackapi             | 1.2                         | TrackAPI-1.2.jar                                   | None                                     |
	| LC    | universalmodcore     | 1.0.1                       | UniversalModCore-1.12.2-forge-1.0.1.jar            | None                                     |
	| LC    | immersiverailroading | 1.8.0-7e0f82                | ImmersiveRailroading-1.12.2-forge-1.8.0-7e0f82.jar | None                                     |
	| LC    | journeymap           | 1.12.2-5.7.1                | journeymap-1.12.2-5.7.1.jar                        | None                                     |
	| LC    | morestonesmod        | 1.0_1.12.2                  | More+Stones(v1.0_1.12.2).jar                       | None                                     |
	| LC    | neid                 | 1.5.4.4                     | NotEnoughIDs-1.5.4.4.jar                           | None                                     |
	| LC    | sheepmilking         | 1.12.2b                     | Pam's Sheep Milking 1.12.2b.jar                    | None                                     |
	| LC    | simplerecipes        | 1.12.2c                     | Pam's Simple Recipes 1.12.2c.jar                   | None                                     |
	| LC    | harvestcraft         | 1.12.2zb                    | Pam's+HarvestCraft+1.12.2zg.jar                    | None                                     |
	| LC    | pamscookables        | 1.1                         | pamscookables-1.1.jar                              | None                                     |
	| LC    | placeableitems       | 3.3                         | placeableitems-3.3.jar                             | None                                     |
	| LC    | ptrmodellib          | 1.0.4                       | PTRLib-1.0.4.jar                                   | None                                     |
	| LC    | rustic               | 1.1.7                       | rustic-1.1.7.jar                                   | None                                     |
	| LC    | rusticthaumaturgy    | 4.4a                        | Rustic Thaumaturgy-4.4a.jar                        | None                                     |
	| LC    | rusticwitchcraft     | 1.0.2                       | rusticwitcraft-1.0.2.jar                           | None                                     |
	| LC    | simpleharvest        | 1.08                        | simpleharvest-1.08.jar                             | None                                     |
	| LC    | stg                  | 1.12.2-1.2.3                | stg-1.12.2-1.2.3.jar                               | None                                     |
	| LC    | tfspellpack          | 1.1.0                       | TFSpellPack-1.1.0-MC1.12.2.jar                     | None                                     |
	| LC    | unlimitedchiselworks | 0.3.4                       | UnlimitedChiselWorks-0.3.4.jar                     | None                                     |
	| LC    | vbe                  | GRADLE:VERSION-GRADLE:BUILD | Vanilla+Builders+Extension-1.12.2-1.0.9.jar        | None                                     |
	| LC    | worldedit            | 6.1.10                      | worldedit-forge-mc1.12.2-6.1.10-dist.jar           | None                                     |
	| LC    | xpfromharvest        | 1.2.0                       | XPFromHarvest-1.12.2-1.2.0.jar                     | None                                     |
	| LC    | llibrary             | 1.7.18                      | LLibrary-1.12.2.jar                                | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LC    | structurize          | 1.12.2-0.10.277-RELEASE     | structurize-1.12.2-0.10.277-RELEASE.jar            | None                                     |
	| LC    | minecolonies         | 1.12.2-0.11.841-ALPHA       | minecolonies-1.12.2-0.11.841-ALPHA-universal.jar   | None                                     |

	Loaded coremods (and transformers): 
Plugin (NotEnoughIDs-1.5.4.4.jar)
  ru.fewizz.neid.asm.Transformer
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
BewitchmentFMLLoadingPlugin (bewitchment-1.12.2-0.0.22.59.jar)
  
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.281.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  team.chisel.ctm.client.asm.CTMTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13399 Compatibility Profile Context 15.201.1151.0' Renderer: 'AMD Radeon HD 6530D'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)

	Patchouli open book context: n/a
	OptiFine Version: OptiFine_1.12.2_HD_U_F5
	OptiFine Build: 20191204-141934
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.13399 Compatibility Profile Context 15.201.1151.0
	OpenGlRenderer: AMD Radeon HD 6530D
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 4

**Comment by Sunconure11** [comment]
How in the actual fuck

Is there any more info you can provide?

**Comment by Sunconure11** [comment]
Were you doing anything specific?
